# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matt Johnescu
title: Marketing Analyst
email: johnescum@gmail.com
website: github.com/mattjohnescu

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  mattjohnescu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mattjohnescu
linkedin_username: matthewjohnescu
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: /profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Matt and I am a Marketing Analyst. I recently graduated from the University of Utah in 2023 with a Bachelor of Science in marketing. Following this I immediately began a Masters of Science in Business Analytics which I finished in December 2024. While completing my Master's degree, I have been working as a Marketing Analyst at Fuel Marketing. Both my academic and professional pursuits have led me on a personal quest to better combine Data Science and Marketing. 

  I am most skilled in: <mark>Marketing Analytics</mark> and <mark>Skiing</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: MSBA Capstone Project, Predictive Maintenance for Swire Coca-Cola
        link: github.com/mattjohnescu/MSBA-Capstone-Project
        # link_text: Project Website
        additional_links:
          - title:  mattjohnescu/MSBA-Capstone-Project
            icon: fab fa-github
            url: github.com/mattjohnescu/MSBA-Capstone-Project
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Machine learning for Preventative Maintenance for Swire Coca-Cola. Honestly the best part of this project was collaborating with my team on a seemingly impossible problem.
        description: | # this will include new lines to allow paragraphs
          Developed a predictive model using lasso regression to identify machines and parts causing unplanned downtime, reducing costly production losses. Delivered actionable insights for preventative maintenance, saving Swire Coca-Cola millions annually while optimizing plant efficiency.
  
      - layout: top-middle
        title: MSBA Practice Capstone Project, Predicting Loan Default Rate
        link: github.com/mattjohnescu/Practice-Capstone-Project
        # link_text: Project Website
        additional_links:
          - title:  mattjohnescu/Practice-Capstone-Project
            icon: fab fa-github
            url: github.com/mattjohnescu/Practice-Capstone-Project
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Everyday individuals with no credit history are subject to unfair loaning practices, even if there is other supporting evidence that they can pay back a loan. The purpose of this project was to identify variables that identify and individuals ability to repay or not repay a loan when for individuals with no credit history. 
        description: | # this will include new lines to allow paragraphs
          Home Credit Default Risk Prediction: Enhanced loan repayment prediction models for Home Credit using LightGBM, SVM, and Linear Regression. Delivered actionable insights to responsibly expand their client base, reduce defaults, and increase profitability by leveraging alternative data and improving decision-making processes. 
  
  
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FUEL Marketing
        link: fuelmarketing.com
        # link_text: fuelmarketing.com
        sub_title: Marketing Analyst
        caption: May 2023 - Present
        quote: >
            Fuel Marketing is a top marketing and creative agency for branding, digital marketing, social media, TV/radio, outdoor, web, SEO, graphic design, PR, and more.
        description: | # this will include new lines to allow paragraphs
            - Managed digital marketing campaigns for over 60 franchise locations, coordinating closely with account managers and web developers. Utilized tools like Power BI and Dashthis to create dashboards that provided clients with comprehensive, data-driven insights and actionable results.
            - Enhanced campaigns by conducting A/B testing and developing data-driven strategies, achieving a 10% performance increase through targeted insights and ad optimization.
            - Created clear, actionable reports and presentations, turning complex data into easily digestible insights for clients and stakeholders.
            - Worked on a cross-functional team to start SEO as a service at Fuel, successfully implemented this service with existing clients and new clients.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of Utah
        caption: 2023 - 2024
        sub_title: MS Business Analytics
        quote: >
          Ranked #5 in the U.S. by TFE Times (2024) and designed to provide the skills necessary to compete in the rapidly growing market for analytics and data science professionals, the David Eccles School of Business Master of Science in Business Analytics (MSBA) program offers a unique blend of innovative curriculum in both the data analytics and business space.
        description: | # this will include new lines to allow paragraphs
          During my Masters program I took the opportunity to pursue combining data science and marketing through a number of courses including **data mining, big data analytics, natural language processing**, all using **Python**, **R**, and **SQL**. 
          - Worked with Swire Coca-Cola to complete my capstone project. Each year Swire is faced with the issue of only meeting 94% of its demand, 60 million dollars worth of this loss is due to machine downtime. By implementing Machine Learning to discover trends and opportunities for Preventative Maintenance in bottling and canning production lines, my team and I were able to discover trends that could cut down on machine downtime by 10-15%.

      - layout: left
        title: The University of Utah
        caption: 2019 - 2023
        sub_title: BS Marketing
        quote: >
          The marketing undergraduate curriculum includes courses in advertising, digital marketing and analytics, strategic marketing, and professional sales.
        description: | # this will include new lines to allow paragraphs
          Took courses in Market Research, Marketing Analytics, International Marketing, Business Strategy. Through my coursework I discovered the potential for using data to make marketing decisions. This fact seemed so important to me that I grew just as passionate about data decision making as I am about marketing, leading me to pursue a masters degree in business analytics.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data science and marketing, some of my other interests and hobbies are:
      - Backpacking
      - Skiing
      - Alpinism
      - Volunteering with the Special Olympics


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
